app/urls.py
from django.contrib import admin
from django.urls import path, include
from oauth2_provider import urls as oauth2_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

djangoblog/apps/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index_view, name="index"),
    path('create/', views.create_view, name="create"),
    path('post/<int:id>/', views.post_view, name="post"),
    path('comment/<int:id>/', views.comment_view, name="comment")
]

djangoblog/apps/oauth/urls.py
from django.urls import path

from . import views

app_name = "oauth"

urlpatterns = [
    path('logout/', views.logout_view, name="logout")
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djangoblog.apps.blog.urls', namespace='blog')),
    path('', include('djangoblog.apps.oauth.urls', namespace='oauth')),
    path('', include('social_django.urls', namespace='social')),
]

tjdjangoblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tjdjangoblog.apps.blog.urls')),
    path('', include('tjdjangoblog.apps.auth.urls')),
    path('', include('social_django.urls', namespace='social'))
]

djangoblog/apps/blog/models.py
from django.db import models # type: ignore
from django.utils.timezone import now # type: ignore
import humanize # type: ignore

def humanize_time_difference(time):
    diff = now() - time
    seconds = diff.total_seconds()

    if seconds < 60:
        return "less than a minute ago"
    elif seconds < 3600:
        return f"{int(seconds // 60)} minutes ago"
    elif seconds < 86400:
        return f"{int(seconds // 3600)} hours ago"
    elif seconds < 604800:
        return f"{int(seconds // 86400)} days ago"
    else:
        return humanize.naturaltime(diff) + " ago"

# Create your models here.
class Comment(models.Model):
    content = models.TextField(max_length=1000)
    poster = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    time_diff = models.CharField(max_length=1000, default="default time")

    def update_time_diff(self):
        self.time_diff = humanize_time_difference(self.created_at)
        self.save()

    def __str__(self):
        if (len(self.content) < 10):
            return self.content
        else:
            return self.content[:10]


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=10000)
    op = models.CharField(max_length=50)
    comments = models.ManyToManyField(Comment)
    created_at = models.DateTimeField(auto_now_add=True)
    time_diff = models.CharField(max_length=1000, default="default time")

    def update_time_diff(self):
        self.time_diff = humanize_time_difference(self.created_at)
        self.save()

    def __str__(self):
        return self.title
    

class PostComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

djangoblog/apps/blog/forms.py
from django import forms
from .models import BlogPost, Comment

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Type comment here'})
        }

blog/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
def index(request):
    return render(request, "blog/index.html")

djangoblog/apps/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404 # type: ignore
from django.urls import reverse # type: ignore
from ..oauth.decorators import login_required
from .models import BlogPost, PostComment
from .forms import BlogPostForm, CommentForm
from django.utils.timezone import now # type: ignore
from humanize import precisedelta # type: ignore
from .tasks import update_blog_times, update_time_specific, update_comment_times

# Create your views here.
def index_view(request):
    posts = BlogPost.objects.order_by('-created_at').values('title', 'content', 'op', 'id', 'created_at', 'time_diff')
    context = {
        "is_authenticated": request.user.is_authenticated,
        "posts": list(posts),
        "user": request.user
    }
    update_blog_times.delay()
    return render(request, "index.html", context)

@login_required
def create_view(request):
    if request.method == "POST":
        form = BlogPostForm(request.POST)
        if (form.is_valid()):
            post = form.save(commit=False)
            post.op = request.user.username
            post.save()
            post.time_diff = precisedelta(now() - post.created_at) + " ago"
            post.save()
            return redirect("blog:index")
    return render(request, "create.html", {"form" : BlogPostForm})

def post_view(request, id):
    post = get_object_or_404(BlogPost, pk=id)
    update_time_specific(post_pk=id)
    update_comment_times(post_pk=id)
    context = {
        "post": post,
        "form": CommentForm,
        "post_id": id,
        "comments": PostComment.objects.filter(blogpost=post).select_related('comment').order_by('-comment__created_at'),
        "is_authenticated": request.user.is_authenticated,
    }
    return render(request, "post.html", context)

@login_required
def comment_view(request, id):
    post = get_object_or_404(BlogPost, pk=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            newcomment = form.save(commit=False)
            newcomment.poster = request.user.username
            newcomment.save()
            update_comment_times(id)
            PostComment.objects.create(comment=newcomment, blogpost=post)
    return redirect(reverse('blog:post', kwargs={'id': id}))

djangoblog/apps/oauth/views.py
from django.shortcuts import redirect
from django.contrib.auth import logout

def logout_view(request):
    if request.user.is_authenticated:
        request.user.access_token = None
        request.user.save()
    logout(request)
    return redirect("blog:index")

djangoblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Django blog{% endblock %}</title>
</head>
    <body>
        <center>
            <h1>Understudy blog project</h1>
            {% block content %}{% endblock %}
        </center>
    </body>
</html>

djangoblog/templates/create.html
{% extends "base.html" %}


{% block content %}
<a href="{% url 'blog:index' %}">Go back to home page</a>
<form action="/create/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

djangoblog/templates/index.html
{% extends "base.html" %}

{% block content %}
                <p>Welcome to the index page!</p>
                {% if is_authenticated %}
                    <p>You are logged in as {{ user }}. <a href="{% url 'oauth:logout' %}">Logout</a></p>

                    <p><a href="{% url 'blog:create' %}">Create a post</a></p>
                {% else %}
                    <a href="{% url 'social:begin' 'ion' %}">Login with Ion</a>
                {% endif %}
                <hr />
                <h2>Latest posts:</h2>
                {% for post in posts %}
                    <a href="{% url 'blog:post' id=post.id %}" style="color:black;text-decoration:none;">
                        <div style="width:70%;text-align:start;border-style:solid;border-width:1px;padding:0px 20px 0px 20px;margin:10px">
                            <h3 style="margin-bottom:0px;">{{post.title}}</h3>
                            <small>Posted by: {{post.op}}, {{post.time_diff}}</small>
                            <p>{{post.content}}</p>
                        </div>
                    </a>
                {% empty %}
                    <p>There are no posts yet!</p>
                {% endfor %}
{% endblock %}

djangoblog/templates/post.html
{% extends "base.html" %}

{% block content %}
                <a href="{% url 'blog:index' %}">Go back to home page</a>
                <div style="width:70%;text-align:start;border-style:solid;border-width:1px;padding:0px 20px 0px 20px;margin:10px">
                    <h3 style="margin-bottom:0px;">{{post.title}}</h3>
                    <small>Posted by: {{post.op}}, {{post.time_diff}}</small>
                    <p>{{post.content}}</p>
                </div>
                {% if is_authenticated %}
                    <form action="/comment/{{post_id}}/" method="post" style="display:flex;flex-direction: column;width:30%;">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit" value="Submit">
                    </form>
                {% else %}
                    <p>Sign in to leave a comment!</p>
                {% endif %}
                
                <hr />
                <h2 style="margin-bottom:0;">Comments:</h2>
                <small>Comment are sorted by creation date.</small>
                {% for comment in comments  %}
                <div style="width:50%;text-align:start;padding:0px 20px 20px 20px;margin:10px">
                    <h4 style="margin-bottom:0;">{{comment.comment.poster}}</h4>
                    <p style="margin-top:2px;">{{comment.comment.content}}</p>
                    <small>{{comment.comment.time_diff}}</small>
                </div>
                {% empty %}
                <p>There are no comments yet!</p>
                {% endfor %}
{% endblock %}